### ISSUE TITLE
The Bug for multithreading using Node-delphi!

### ISSUE THREAD

**Issue by heimo88** [BazisSoft/node-delphi#9] opened 2017-03-09 03:38 UTC
* **Version**: dev
* **Platform**: window 10 64
* **Subsystem**: delphi 10.1.2

I have compress the code with zip, but I can't upload that type, I change the ext to txt, you can download the file and change it to .zip.

In the demo I created 3 thread with diff js file, like 1.js 2.js 3.js and them call system.log  23 24 25, but it some times will show  25 24 25 and others.

and there are another issue, I can't create TJSEngine same time, i must use EnterCriticalSection(MyCs); //
        try
          Eng := TJSEngine.Create;
        finally
          LeaveCriticalSection(MyCs); //
        end;

if I create same time it will show an av error.
Please check them.

Thanks!

[demo.txt](https://github.com/BazisSoft/node-delphi/files/829693/demo.txt)

**Comment by heimo88** [comment] 2017-03-09 03:43
@Let0s 
I have upload the demo code , please check it,

 Thank you!

**Comment by heimo88** [comment] 2017-03-09 07:10
I test some times you can see the result:
---------------------------start----------------------------------
2 --> 25

1 --> 23

3 --> 25

---------------------------start----------------------------------
1 --> 25

2 --> 24

3 --> 25

---------------------------start----------------------------------
1 --> 25

3 --> 25

2 --> 24


---------------------------start----------------------------------
1 --> 25

2 --> 24

3 --> 25

---------------------------start----------------------------------
1 --> 25

2 --> 24

3 --> 25

**Comment by smeshch** [comment] 2017-03-12 07:56
About creating Engines at same time: it was fixed since 927a13a7016aebe42854541e56d76e85946c1d0f commit: there was added "InitializeNode" function for initializing node manually before creating any engine.
About executing different scripts: I checked it and I will try to fix it.

**Comment by heimo88** [comment] 2017-03-12 11:51
Great! Thank you!

**Comment by heimo88** [comment] 2017-03-22 08:21
@Let0s Hi, 
 What about this issue? is it hard to fix?

**Comment by smeshch** [comment] 2017-03-23 07:27
@liang1zhou I think there is a problem, caused by one of node's global variable and it will take some time (I dont know how much) to find it.

**Comment by heimo88** [comment] 2017-03-23 11:08
@Let0s  I found that the V8 Engine did not support the multithreading, maybe it is the reason?

**Comment by smeshch** [comment] 2017-03-24 06:17
I think so. I know, than node.js use libuv to make async code run, but it's not multithreaded. Use CriticalSection to avoid this bug. I will close this issue, but I will try to find another way to resolve this problem.

**Closed as completed by smeshch** 2017-03-24 06:17 UTC
Labels: bug
